# Generated by Django 4.1.3 on 2022-11-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NYCBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "NYC buildings",
            },
        ),
    ]
