# Generated by Django 4.1.3 on 2022-11-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opendata", "0002_nycbuilding_building_city_nycbuilding_gross_sqft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nycbuilding",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
