# Generated by Django 4.1.3 on 2022-11-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opendata", "0003_alter_nycbuilding_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nycbuilding",
            name="yrbuilt",
            field=models.IntegerField(default=-1),
        ),
    ]
